mydata<-read.delim("household_power_consumption.txt",header=T,sep=";",stringsAsFactors=FALSE)
mydata_sub<-subset(mydata,(Date=="1/2/2007"))
mydata_sub2<-subset(mydata,(Date=="2/2/2007"))
mydata_sub3<-rbind(mydata_sub,mydata_sub2)
library(dplyr)
mydata1<-mutate(mydata_sub3,datetime=paste(Date,Time))
datetime2=strptime(mydata1$datetime,"%d/%m/%Y %H:%M:%S")
mydata4<-cbind(mydata1,datetime2)
par(mfrow=c(2, 2))
plot(mydata4$datetime2,mydata4$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
plot(mydata4$datetime2,mydata4$Voltage,type="l",ylab="Voltage",xlab="")

plot(mydata4$datetime2,mydata4$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
par(new=T)
plot(mydata4$datetime2,mydata4$Sub_metering_2,type="l",axes=F,col="red",ylab="",xlab="")
par(new=T)
plot(mydata4$datetime2,mydata4$Sub_metering_3,type="l",axes=F,col="blue",ylab="",xlab="")
plot(mydata4$datetime2,mydata4$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="")
