mydata<-read.delim("household_power_consumption.txt",header=T,sep=";",stringsAsFactors=FALSE)
mydata_sub<-subset(mydata,(Date=="1/2/2007"))
mydata_sub2<-subset(mydata,(Date=="2/2/2007"))
mydata_sub3<-rbind(mydata_sub,mydata_sub2)
library(dplyr)
mydata1<-mutate(mydata_sub3,datetime=paste(Date,Time))
datetime2=strptime(mydata1$datetime,"%d/%m/%Y %H:%M:%S")
mydata4<-cbind(mydata1,datetime2)
plot(mydata4$datetime2,mydata4$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")